/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.openconnectors.connect;

import org.openconnectors.config.Config;

import java.io.Closeable;
import java.io.Serializable;
import java.util.Collection;

/**
 * Interface for a message collector specifically meant for running with a Source Connector
 *
 * @param <T>
 */
public interface Collector<T> extends AutoCloseable, Serializable {

    /**
     * Setup Collector with a config
     * @param config
     * @throws Exception
     */
    void setup(Config config) throws Exception;

    /**
     * Receive messages generated by a source
     *
     * @param messages
     * @throws Exception
     */
    void collect(Collection<T> messages) throws Exception;
}
